#!/bin/sh

echo "🔍 Running pre-push validation..."
echo "  - Type checking..."
#npm run type-check || exit 1
# npx lint-staged

echo "  - Linting..."
npm run lint || exit 1

echo "  - Building..."
npm run build || exit 1

echo "✅ All checks passed!"
